version: '2.3'

services:
  telescopy-service:
    environment:
      - "LISTEN_PORT=[::]:80"
    build: ./src
    networks:
      telescopy-intern:
      app_net:
        ipv6_address: 2001:db7:3200::20
    volumes:
      - ./src:/app
    depends_on:
      - redis
  redis:
    networks:
      telescopy-intern:
    image: redis
    ports:
      - "6379:6379"

networks:
  telescopy-intern:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:db7:3200::/64
          gateway: 2001:db7:3200::1

