version: '3'

services:
  telescopy-service:
    build: ./src
    volumes:
      - ./src:/app
    ports:
      - "8000:80"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"