version: '3'

services:
  telescopy-service:
    build: ./src
    volumes: 
      - ./src:/usr/src/app
    ports: 
      - 8000:8000

  website:
    image: php:apache
    volumes:
    - ./src/front/www:/var/www/html
    ports:
      - 5051:80
