version: '3.6'
services:
  telescopy-backend:
    build: .
    environment:
    - MONGO_ENABLED=1
    - MONGO_HOST=telescopy-db
    - MONGO_PORT=27017
    - MONGO_USER=ipv6islove
    - MONGO_PASSWORD=dockerislove
    image: 10.13.37.7:5000/telescopy-backend
    networks:
    - bridge
    - enoverlay
  telescopy-frontend:
    depends_on:
    - telescopy-backend
    deploy:
      labels:
      - traefik.enable=true
      - traefik.backend=telescopy-checker
      - traefik.docker.network=enoverlay
      - traefik.frontend.rule=Host:telescopy.checker.enowars.com,service19.checker.enowars.com
      - traefik.port=80
      replicas: 1
    image: nginx:1.13-alpine
    networks:
    - enoverlay
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf

  telescopy-db:
    image: mongo
    networks:
      - enoverlay
    volumes:
      - telescopy_db_data:/data/db
#we need to fix the node otherwise the volumes are lost after migration :/
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==blade5"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ipv6islove
      MONGO_INITDB_ROOT_PASSWORD: dockerislove

networks:
  bridge:
    external: true
  enoverlay:
    external: true

volumes:
  telescopy_db_data:

configs:
  nginx_config: 
    file: ./nginx.conf