version: '2.3'
services:
  telescopy-backend:
    build: .
    networks:
      telescopy-checker-network:
        ipv6_address: fd00:1337:0:cecc:8::2
  telescopy-frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - telescopy-backend
    networks:
      telescopy-checker-network:
        ipv6_address: fd00:1337:0:cecc:8::1

networks:
  telescopy-checker-network:
    external: true

