version: '2.3'
services:
  telescopy-backend:
    build: .
    networks:
      telescopy-checker-intern:
      telescopy-checker-network:
        ipv6_address: fd00:1337:0:abed::1
  telescopy-frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - telescopy-backend
    ports:
      - 5001:80
    networks:
      telescopy-checker-intern:
      telescopy-checker-network:
        ipv6_address: fd00:1337:0:abed::2

networks:
  telescopy-checker-intern:
  telescopy-checker-network:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:1337:0:abed::/64
          gateway: fd00:1337:0:abed::ffff

