version: '3'
services:
  telescopy-backend:
    image: 10.13.37.7:5000/telescopy-backend
    build: .
    networks:
      - bridge
      - enoverlay
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=checkerdb_mongo_1
      - MONGO_PORT=27017
      - MONGO_USER=ipv6islove
      - MONGO_PASSWORD=dockerislove
  telescopy-frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - telescopy-backend
    networks:
      - enoverlay
    labels:
        - "traefik.enable=true"
        - "traefik.backend=telescopy-checker"
        - "traefik.docker.network=enoverlay"
        - "traefik.frontend.rule=Host:telescopy.checker.enowars.com,service19.checker.enowars.com"
        - "traefik.port=80"

networks:
   bridge:
     external: true
   enoverlay:
     external: true
